server:
  port: 8000
spring:
  application:
    name: eureka-server-8000

eureka:
  instance:
    hostname: eureka-8000.liangqinghai.cn
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-8001.liangqinghai.cn
