server:
  port: 9003

spring:
  application:
    name: alibaba-user-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
