server:
  port: 9010
spring:
  application:
    name: user-consumer
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: 127.0.0.1
      port: 8500
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://eureka-8001.liangqinghai.cn/eureka,http://eureka-8000.liangqinghai.cn/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: user-consumer-9010

